import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

async function render(pathname="/"){
 const workerUrl=new URL("../dist/server/index.js",import.meta.url);workerUrl.searchParams.set("test",`${process.pid}-${Date.now()}-${pathname}`);const {default:worker}=await import(workerUrl.href);return worker.fetch(new Request(`http://localhost${pathname}`,{headers:{accept:"text/html"}}),{ASSETS:{fetch:async()=>new Response("Not found",{status:404})}},{waitUntil(){},passThroughOnException(){}})
}
test("server-renders the premium Northline experience",async()=>{const response=await render();assert.equal(response.status,200);const html=await response.text();assert.match(html,/<title>Northline — Residential engineering, reimagined<\/title>/i);assert.match(html,/Homes engineered/);assert.match(html,/Early-stage estimator/);assert.match(html,/aria-label="Primary navigation"/);assert.match(html,/>Home<\/a>/);assert.match(html,/role="tablist"/);assert.doesNotMatch(html,/blueprint-house|site-shell|codex-preview/i)});
test("renders all routes and interactive motion states",async()=>{for(const [path,copy] of [["/projects","Homes shaped"],["/services","The whole house"],["/studio","Small studio"],["/journal","Ideas for homes"]]){const response=await render(path);assert.equal(response.status,200);assert.match(await response.text(),new RegExp(copy))}const [site,css,layout]=await Promise.all([readFile(new URL("../app/site.tsx",import.meta.url),"utf8"),readFile(new URL("../app/globals.css",import.meta.url),"utf8"),readFile(new URL("../app/layout.tsx",import.meta.url),"utf8")]);assert.match(site,/IntersectionObserver/);assert.match(site,/motionThreshold/);assert.match(site,/0\.45/);assert.match(site,/requestAnimationFrame/);assert.match(site,/type="range"/);assert.match(site,/aria-expanded/);assert.match(css,/@keyframes headlineIn/);assert.match(css,/@keyframes cardContentIn/);assert.match(css,/clip-path:none!important/);assert.match(css,/motion-left/);assert.match(css,/motion-flip/);assert.match(css,/motion-zoom/);assert.match(layout,/motion-force motion-loading/)})
