"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { ArrowRight, Buildings, Calculator, CaretDown, Check, CirclesThree, Cube, Gauge, House, Leaf, Ruler, ShieldCheck, Sparkle, X } from "@phosphor-icons/react";

type Page = "home" | "projects" | "services" | "studio" | "journal";
type Project = { name:string; place:string; year:string; image:string; type:string; scope:string };
const navigation = [{label:"Projects",href:"/projects",page:"projects"},{label:"Services",href:"/services",page:"services"},{label:"Studio",href:"/studio",page:"studio"},{label:"Journal",href:"/journal",page:"journal"}] as const;
const projects:Project[]=[
  {name:"Pine Court House",place:"New Cairo",year:"2025",image:"/images/villa-hero.jpg",type:"New home",scope:"Structure · Climate"},
  {name:"Folded Stone Villa",place:"Amman",year:"2024",image:"/images/concrete-house.jpg",type:"New home",scope:"Structure · Coordination"},
  {name:"Garden Threshold",place:"Alexandria",year:"2024",image:"/images/garden-house.jpg",type:"Retrofit",scope:"Climate · Envelope"},
  {name:"The Amber Stair",place:"Dubai",year:"2023",image:"/images/staircase.jpg",type:"Interior",scope:"Detail · Fabrication"}
];
const services=[
  {id:"structure",label:"Structure",icon:Cube,title:"Strength, with less material.",copy:"We shape clear load paths and right-size every member early, giving the architecture more freedom and the build less uncertainty.",metric:"18%",metricLabel:"average material reduction",notes:["Concept structures","Detailed calculations","Construction coordination"]},
  {id:"climate",label:"Climate",icon:Leaf,title:"Comfort designed into the plan.",copy:"Sun, shade, airflow and thermal mass become architectural ingredients—not equipment added after the design is finished.",metric:"41%",metricLabel:"lower modeled energy demand",notes:["Passive strategy","Thermal modelling","Daylight analysis"]},
  {id:"coordination",label:"Coordination",icon:CirclesThree,title:"One model. Fewer surprises.",copy:"Structure, envelope and services are resolved together before they reach site, preserving both the idea and the programme.",metric:"3.2×",metricLabel:"fewer site clarifications",notes:["Federated BIM","Detail packages","Tender support"]}
];
const markRouteStatic=()=>{document.documentElement.classList.add("motion-static");document.documentElement.classList.remove("motion-loading")};

export function Site({page}:{page:Page}){
  const [notice,setNotice]=useState(false);
  useEffect(()=>{const open=()=>setNotice(true);window.addEventListener("northline:open-notice",open);return()=>window.removeEventListener("northline:open-notice",open)},[]);
  useEffect(()=>{
    const staticMotion=document.documentElement.classList.contains("motion-static");
    document.documentElement.classList.add("motion-force");
    if(staticMotion)document.documentElement.classList.remove("motion-loading");else document.documentElement.classList.add("motion-loading");
    const selector=["[data-reveal]",".hero-console > *",".client-strip > *",".intro > *",".intro h2",".intro-copy > *",".section-heading > *",".service-tabs > *",".service-panel-copy > *",".metric-stage > *",".metric-card > *",".featured-caption > *",".project-mini-grid > *",".project-info > *",".numbers > *",".numbers > div > *",".estimator > *",".estimator-card > *",".estimator-card label",".estimate-result > *",".process-grid > *",".process-grid article > *",".faq > *",".faq-list > *",".faq-list button > *",".subhero > *",".archive-grid > *",".services-page > *",".services-page article > *",".studio-story > *",".studio-story article > *",".values > *",".values article > *",".journal > *",".journal article > *",".callout > *",".footer > *",".footer-bottom > *"].join(",");
    const counters=new Map<Element,number>();
    const nodes=Array.from(document.querySelectorAll<HTMLElement>(selector)).filter(node=>!node.classList.contains("ambient")&&!node.classList.contains("metric-glow")&&!node.classList.contains("callout-glow"));
    const variants=["motion-mask","motion-scale","motion-left","motion-right","motion-soft","motion-sweep","motion-flip","motion-zoom"];
    nodes.forEach(node=>{const parent=node.parentElement;if(!parent)return;const index=counters.get(parent)??0;counters.set(parent,index+1);node.classList.remove(...variants);node.classList.add("motion-item");if(node.matches("h1,h2,h3,.section-heading"))node.classList.add("motion-mask");else if(node.matches("p,.eyebrow,.project-info small,.estimate-result span,.estimate-result small"))node.classList.add("motion-soft");else if(node.matches(".button,.text-link,.faq-list button>*"))node.classList.add("motion-sweep");else if(node.matches(".service-tabs button,.filter-row button"))node.classList.add("motion-flip");else if(node.matches(".numbers>div,.metric-card,.estimate-result"))node.classList.add("motion-zoom");else if(node.matches(".project-tile,.process-grid article,.values article,.journal article"))node.classList.add(index%2?"motion-right":"motion-left");else if(node.matches(".featured-project,.metric-stage,.studio-story>div"))node.classList.add("motion-scale");node.dataset.motionThreshold=node.matches(".hero-console,.hero-console>*")?"0.45":node.matches(".motion-scale,.motion-left,.motion-right")?"0.28":"0.16";node.style.setProperty("--motion-delay",`${Math.min(index*120,600)}ms`)});
    const close=(e:KeyboardEvent)=>e.key==="Escape"&&setNotice(false);window.addEventListener("keydown",close);
    if(staticMotion){nodes.forEach(node=>node.classList.add("is-visible"));return()=>window.removeEventListener("keydown",close)}
    const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{const node=entry.target as HTMLElement;const required=Number(node.dataset.motionThreshold??.16);if(entry.isIntersecting&&entry.intersectionRatio>=required){node.classList.add("is-visible");observer.unobserve(node)}}),{threshold:[0,.08,.16,.28,.45,.65,1],rootMargin:"0px 0px -6% 0px"});
    let secondFrame=0;let revealTimer=0;const firstFrame=requestAnimationFrame(()=>{secondFrame=requestAnimationFrame(()=>{nodes.forEach(node=>observer.observe(node));revealTimer=window.setTimeout(()=>document.documentElement.classList.remove("motion-loading"),180)})});
    return()=>{cancelAnimationFrame(firstFrame);cancelAnimationFrame(secondFrame);clearTimeout(revealTimer);document.documentElement.classList.remove("motion-loading");observer.disconnect();window.removeEventListener("keydown",close)}
  },[page]);
  return <div className={`site page-${page}`}>
  {page==="home"&&<Home openNotice={()=>setNotice(true)}/>} {page==="projects"&&<Projects openNotice={()=>setNotice(true)}/>} {page==="services"&&<Services openNotice={()=>setNotice(true)}/>} {page==="studio"&&<Studio openNotice={()=>setNotice(true)}/>} {page==="journal"&&<Journal/>}<Footer openNotice={()=>setNotice(true)}/>{notice&&<Notice close={()=>setNotice(false)}/>}</div>
}

function Home({openNotice}:{openNotice:()=>void}){
 const [active,setActive]=useState(0),[area,setArea]=useState(320),[complexity,setComplexity]=useState(2),[faq,setFaq]=useState<number|null>(0);const estimate=useMemo(()=>Math.round(area*(58+complexity*13)/1000)*1000,[area,complexity]);const selected=services[active];
 return <main><section className="hero"><div className="ambient ambient-one"/><div className="ambient ambient-two"/><div className="hero-inner"><div className="eyebrow hero-eyebrow"><Sparkle weight="fill"/> Residential engineering, reimagined</div><h1><span>Homes engineered</span><span>to feel <em>effortless.</em></span></h1><p>We bring structure, climate and construction detail into one calm system—so ambitious homes are simpler to build and better to live in.</p><div className="hero-actions"><button className="button button-glow" onClick={openNotice}><span>Discuss your house</span><ArrowRight/></button><Link className="button button-light" href="/projects" onClick={markRouteStatic}><span>Explore our work</span></Link></div><div className="proof"><div className="avatars"><span>MA</span><span>LY</span><span>OK</span></div><p><strong>4.9 / 5</strong><br/>from private clients & architects</p></div></div>
 <div className="hero-console" data-reveal><article className="console-card"><div className="card-icon"><Cube/></div><span>Structure</span><strong>Resolved early.</strong><div className="mini-beams"><i/><i/><i/><i/></div><small><Check weight="bold"/> 14 coordination checks passed</small></article><article className="console-card"><div className="card-icon"><Gauge/></div><span>Comfort model</span><strong>24.1°C</strong><div className="comfort-chart"><i/><i/><i/><i/><i/><i/><i/><i/></div><small>Passive comfort · June</small></article><article className="console-card"><div className="card-icon"><Ruler/></div><span>Drawing set</span><strong>Issue 04</strong><div className="detail-lines"><i/><i/><i/></div><small><span className="live-dot"/> Live coordination</small></article></div><div className="client-strip"><span>Trusted on residences with</span><b>Atelier N</b><b>FORM / 04</b><b>Studio Locus</b><b>Field Office</b></div></section>
 <section className="intro section" data-reveal><div><div className="eyebrow">A quieter kind of expertise</div><h2>The best engineering is the part of a home you never have to think about.</h2></div><div className="intro-copy"><p>Northline is an independent residential engineering studio. We turn complex constraints into clear decisions, from the first sketch to the final site review.</p><Link className="text-link" href="/studio" onClick={markRouteStatic}>Meet the studio <ArrowRight/></Link></div></section>
 <section className="feature-band section"><Heading eyebrow="One coordinated system" title={<>Three disciplines.<br/>One line of thought.</>} copy="Switch between the systems we resolve together on every project."/><div className="service-tabs" role="tablist">{services.map((s,i)=>{const Icon=s.icon;return <button key={s.id} role="tab" aria-selected={active===i} onClick={()=>setActive(i)}><Icon/><span>{s.label}</span><small>0{i+1}</small></button>})}</div><div className="service-panel" key={selected.id}><div className="service-panel-copy"><span className="panel-index">0{active+1} / 03</span><h3>{selected.title}</h3><p>{selected.copy}</p><ul>{selected.notes.map(note=><li key={note}><Check weight="bold"/>{note}</li>)}</ul><Link className="button button-light" href="/services" onClick={markRouteStatic}><span>Explore this service</span><ArrowRight/></Link></div><div className="metric-stage"><div className="metric-glow"/><div className="metric-card"><span>Measured outcome</span><strong>{selected.metric}</strong><p>{selected.metricLabel}</p><div className="metric-bars">{[48,66,54,78,68,88,82,96].map((h,i)=><i key={i} style={{height:`${h}%`}}/>)}</div></div><div className="status-chip"><ShieldCheck weight="fill"/> Model verified</div></div></div></section>
 <section className="work section"><Heading eyebrow="Selected residences" title={<>Clarity, made physical.</>} link="View all projects"/><div className="featured-project" data-reveal><img src="/images/villa-hero.jpg" alt="Modern residence framed by garden landscaping"/><div className="featured-caption"><div><span>01 · New Cairo · 2025</span><h3>Pine Court House</h3></div><p>A low-energy family home where structure, shade and landscape work as one.</p></div></div><div className="project-mini-grid">{projects.slice(1).map((p,i)=><ProjectTile key={p.name} project={p} index={i+2}/>)}</div></section>
 <section className="numbers section" data-reveal><div><strong>72</strong><span>homes completed</span></div><div><strong>11</strong><span>years in practice</span></div><div><strong>6</strong><span>climate regions</span></div><div><strong>94%</strong><span>repeat referrals</span></div></section>
 <section className="estimator section"><div className="estimator-copy" data-reveal><div className="eyebrow">Early-stage estimator</div><h2>Give the first conversation a useful starting point.</h2><p>Adjust the project profile for an indicative engineering fee range. Every real proposal is tailored after a design review.</p></div><div className="estimator-card" data-reveal><div className="estimator-head"><span><Calculator/> Project snapshot</span><small>Indicative only</small></div><label><span>Approximate floor area <b>{area} m²</b></span><input type="range" min="120" max="900" step="10" value={area} onChange={e=>setArea(Number(e.target.value))}/></label><label><span>Project complexity <b>{["Simple","Considered","Complex"][complexity-1]}</b></span><input type="range" min="1" max="3" value={complexity} onChange={e=>setComplexity(Number(e.target.value))}/></label><div className="estimate-result"><span>Estimated design fee</span><strong>EGP {estimate.toLocaleString()} – {(estimate*1.28).toLocaleString()}</strong><small>Structural, performance and coordination scope</small></div><button className="button button-glow full" onClick={openNotice}><span>Request a tailored scope</span><ArrowRight/></button></div></section>
 <section className="process section"><Heading eyebrow="From sketch to handover" title={<>Continuity creates quality.</>}/><div className="process-grid">{[["01","Read the place","Climate, ground, constraints and daily rituals."],["02","Resolve the system","Structure, envelope and services modelled together."],["03","Make it buildable","Precise information coordinated before site."],["04","Stay with the work","Focused reviews through construction and handover."]].map(item=><article key={item[0]} data-reveal><span>{item[0]}</span><div className="process-icon"><Check/></div><h3>{item[1]}</h3><p>{item[2]}</p></article>)}</div></section>
 <section className="faq section"><div data-reveal><div className="eyebrow">Frequently asked</div><h2>Before we begin.</h2></div><div className="faq-list">{[["When should an engineer join the project?","Ideally during the first design studies. Early involvement gives the architect more freedom and prevents expensive redesign later."],["Do you work directly with homeowners?","Yes. We work with homeowners, architects and design-led contractors, adapting our communication to each team."],["Can you support construction on site?","Yes. Our scopes can include tender review, key-stage inspections, contractor queries and final handover support."],["Do you take projects outside Egypt?","Yes. We collaborate remotely and partner with locally licensed engineers where approvals require it."]].map((item,i)=><article className={faq===i?"open":""} key={item[0]}><button onClick={()=>setFaq(faq===i?null:i)} aria-expanded={faq===i}><span>{item[0]}</span><CaretDown/></button><div><p>{item[1]}</p></div></article>)}</div></section><Callout openNotice={openNotice}/></main>
}

function Heading({eyebrow,title,copy,link}:{eyebrow:string;title:React.ReactNode;copy?:string;link?:string}){return <div className="section-heading" data-reveal><div><div className="eyebrow">{eyebrow}</div><h2>{title}</h2></div>{copy?<p>{copy}</p>:link?<Link className="text-link" href="/projects" onClick={markRouteStatic}>{link}<ArrowRight/></Link>:null}</div>}
function Projects({openNotice}:{openNotice:()=>void}){const [filter,setFilter]=useState("All");const filtered=filter==="All"?projects:projects.filter(p=>p.type===filter);return <main><SubHero tag="Project archive" title={<>Homes shaped by<br/><em>clear systems.</em></>} copy="New homes, careful retrofits and exact interiors across six climate regions."/><section className="archive section"><div className="filter-row" role="tablist">{["All","New home","Retrofit","Interior"].map(item=><button key={item} aria-selected={filter===item} onClick={()=>setFilter(item)}>{item}</button>)}</div><div className="archive-grid">{filtered.map((p,i)=><ProjectTile key={p.name} project={p} index={i+1}/>)}</div></section><Callout openNotice={openNotice}/></main>}
function Services({openNotice}:{openNotice:()=>void}){return <main><SubHero tag="What we do" title={<>The whole house,<br/><em>resolved together.</em></>} copy="Technical depth without the fragmented process. One studio stays with the work from first principles to final detail."/><section className="services-page section">{services.map((s,i)=>{const Icon=s.icon;return <article key={s.id} data-reveal><span>0{i+1}</span><div className="service-page-icon"><Icon/></div><div><h2>{s.label}</h2><p>{s.copy}</p></div><ul>{s.notes.map(n=><li key={n}><Check/>{n}</li>)}</ul></article>})}</section><Callout openNotice={openNotice}/></main>}
function Studio({openNotice}:{openNotice:()=>void}){return <main><SubHero tag="Independent by design" title={<>Small studio.<br/><em>Deep attention.</em></>} copy="A residential engineering practice built for close collaboration, exact thinking and a human scale of work."/><section className="studio-story section" data-reveal><div><img src="/images/garden-house.jpg" alt="A calm modern home opening to a planted garden"/></div><article><div className="eyebrow">Our point of view</div><h2>We keep the team close to the decisions.</h2><p>Northline was founded in 2015 to bridge the space between engineering rigour and architectural intent. Our senior engineers stay directly involved, from the first conversation through the last inspection.</p><p>That continuity means fewer hand-offs, clearer documents and a house that holds onto its best ideas all the way to site.</p><button className="button button-dark" onClick={openNotice}><span>Meet for a project review</span><ArrowRight/></button></article></section><section className="values section">{[["01","Calm clarity","Technical complexity becomes decisions everyone can understand."],["02","Useful restraint","We use only what the house needs—and make every element work harder."],["03","Close attention","Senior thinking stays present in drawings, meetings and reviews."],["04","Long horizons","Durability, adaptability and comfort guide every calculation."]].map(item=><article data-reveal key={item[0]}><span>{item[0]}</span><h3>{item[1]}</h3><p>{item[2]}</p></article>)}</section><Callout openNotice={openNotice}/></main>}
function Journal(){return <main><SubHero tag="Field notes" title={<>Ideas for homes<br/>that <em>endure.</em></>} copy="Short observations on structure, climate, craft and the decisions that make a house feel resolved."/><section className="journal section">{projects.map((p,i)=><article key={p.name} data-reveal><img src={p.image} alt=""/><div><span>Field note · 0{i+1}</span><h2>{["Why the best structure begins with the plan","The quiet work of a shaded threshold","Drawing details that contractors can trust","Comfort is a spatial decision first"][i]}</h2><p>{["6 min read","4 min read","7 min read","5 min read"][i]}</p></div></article>)}</section></main>}
function SubHero({tag,title,copy}:{tag:string;title:React.ReactNode;copy:string}){return <section className="subhero"><div className="ambient ambient-one"/><div className="eyebrow">{tag}</div><h1>{title}</h1><p>{copy}</p></section>}
function ProjectTile({project,index}:{project:Project;index:number}){return <article className="project-tile" data-reveal><div className="project-image"><img src={project.image} alt={`${project.name}, ${project.place}`}/><span>0{index}</span></div><div className="project-info"><div><h3>{project.name}</h3><p>{project.place} · {project.year}</p></div><small>{project.scope}</small></div></article>}
function Callout({openNotice}:{openNotice:()=>void}){return <section className="callout section"><div className="callout-glow"/><div className="eyebrow">Have a house in mind?</div><h2>Let’s make the difficult<br/>parts feel simple.</h2><button className="button button-glow" onClick={openNotice}><span>Start a conversation</span><ArrowRight/></button><small>Typical response within two working days</small></section>}
function Footer({openNotice}:{openNotice:()=>void}){return <footer className="footer"><Link className="logo" href="/" onClick={markRouteStatic}><span className="logo-mark"><House weight="fill"/></span><span>Northline<small>House engineering</small></span></Link><div>{navigation.map(item=><Link key={item.href} href={item.href} onClick={markRouteStatic}>{item.label}</Link>)}</div><div><span>New Cairo · Egypt</span><button onClick={openNotice}>hello@northline.engineering</button></div><div className="footer-bottom"><span>© 2026 Northline Studio</span><span>Portfolio concept · No client data collected</span><button onClick={openNotice}>Privacy</button></div></footer>}
function Notice({close}:{close:()=>void}){return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&close()}><div className="modal" role="dialog" aria-modal="true"><button className="modal-close" onClick={close} aria-label="Close"><X/></button><div className="modal-symbol"><Buildings weight="fill"/></div><div className="eyebrow">Portfolio demonstration</div><h2>This enquiry is intentionally offline.</h2><p>Northline is a fictional studio created as a portfolio concept. To respect your privacy, this demonstration does not collect, store or transmit contact details.</p><button className="button button-dark" onClick={close}><span>Return to the experience</span><ArrowRight/></button></div></div>}
